name: bldrs
description: The Builder's Network
publish_to: "none"

# https://developer.android.com/studio/publish/versioning
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

#  alphabet_list_scroll_view: ^2.0.0 // has version conflict with stopwatch timer package
  #  alphabet_list_scroll_view_fix: ^2.0.2
  animated_text_kit: ^4.2.1
  another_flushbar: ^1.10.26
  awesome_notifications: ^0.6.21
  bldrs_theme:
    git:
      url: https://github.com/RagehAz/bldrs_theme.git
  rest:
    git:
      url: https://github.com/RagehAz/rest.git
  widget_fader:
    git:
      url: https://github.com/RagehAz/widget_fader.git
#  super_image:
#    git:
#      url: https://github.com/RagehAz/super_image.git

  #  bldrs_ui:
  #    git:
  #      url: https://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@github.com/Bldrs-net/bldrs_ui.git

  clipboard: ^0.1.3
  crop_your_image: ^0.7.0
  cloud_firestore: ^4.0.3
  cloud_functions: ^4.0.3
  connectivity_plus: ^2.3.0
#  contacts_service: ^0.6.3
  device_info_plus: ^7.0.1
  dismissible_page: ^0.7.3
  #  dio: ^4.0.1
  email_validator: ^2.0.1
  #  esys_flutter_share: ^1.0.1
  exif: ^3.0.1
  file_picker: ^5.2.0+1
  firebase_app_check: ^0.1.1+2
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  firebase_database: ^10.0.3
  firebase_dynamic_links: ^5.0.3
  firebase_messaging: ^14.0.3
  firebase_storage: ^11.0.3
  flutter_svg: ^1.0.3
  flutter_cache_manager: ^3.3.0
  flutter_facebook_auth: ^4.0.1
  flutter_keyboard_visibility: ^5.3.0
  flutter_local_notifications: ^9.0.1
  #  flutter_launcher_icons: ^0.8.1
  flutter_pdfview: ^1.2.3
  flutter_spinkit: ^5.1.0
  flutter_swiper: ^1.1.6
  geolocator: ^9.0.1
  geocoding: ^2.0.1
  google_maps_flutter: ^2.1.0
  google_mobile_ads: ^1.3.0
  google_sign_in: ^5.2.0
  http: ^0.13.4
  image: ^3.0.8
  image_editor: ^1.0.2 # required for SuperFilteredImage
  image_cropping: ^0.0.12
  intl: ^0.17.0
  just_audio: ^0.9.24
  location: ^4.4.0
  mailer: ^5.2.0
  matrix_gesture_detector: ^0.1.0
  matrix2d: ^1.0.2
  matrix4_transform: ^2.0.1
  modal_bottom_sheet: ^2.0.0
  #  modal_progress_hud: ^0.1.3
  package_info_plus: ^3.0.1
  page_transition: ^2.0.4
  path: ^1.8.0
  path_provider: ^2.0.6
  permission_handler: ^10.0.0
  provider: ^6.0.3
  screenshot: ^1.2.3
  #  scroll_snap_list: ^0.8.2
  sembast: ^3.1.1
  share: ^2.0.4
  shared_preferences: ^2.0.8
  #  sqflite: ^2.0.0+4
  stop_watch_timer: ^1.5.0
  translator: ^0.1.7
  url_launcher: ^6.1.4
  video_player: ^2.2.10
  wechat_assets_picker: ^7.3.2
  wechat_camera_picker: ^3.4.0
  websafe_svg: ^2.0.0+1 # will check
  webview_flutter: ^3.0.0 # will delete
  wheel_chooser: ^1.0.0
  tree_view: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  #  flutter_launcher_name: ^0.0.1
  lint: ^1.0.0

flutter_launcher_name:
  name: "Bldrs.net"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/aw/aw_bldrs_app_icon.png"
  adaptive_icon_background: "assets/aw/aw_bldrs_app_icon.png"
  adaptive_icon_foreground: "assets/aw/aw_bldrs_app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/aw/
    - assets/icons/
    - assets/icons/keywords/
    - assets/icons/specs/
    - assets/icons/flags/
    - assets/languages/
    - assets/planet/
    - assets/sounds/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: BldrsHeadlineFont
      fonts:
        - asset: assets/fonts/bldrs_font_bold.ttf

    - family: BldrsBodyFont
      fonts:
        - asset: assets/fonts/bldrs_font_regular.ttf

    - family: EnglishHeadline
      fonts:
        - asset: assets/fonts/arabic/BldrsFont.ttf

    - family: EnglishBody
      fonts:
        - asset: assets/fonts/english/Roboto_Thin.ttf
        - asset: assets/fonts/english/Roboto_ThinItalic.ttf

    - family: ArabicHeadline
      fonts:
        - asset: assets/fonts/arabic/BldrsFont.ttf

    - family: ArabicBody
      fonts:
        - asset: assets/fonts/arabic/Tajawal_Light.ttf
        - asset: assets/fonts/arabic/Tajawal_Regular.ttf
        - asset: assets/fonts/arabic/BldrsFont.ttf
